require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const Product = require('./Product');
const User = require('./User');

const products = [
  { id:1, title:"Wireless Bluetooth Earbuds Pro with Noise Cancellation", category:"Electronics", price:1899, oldPrice:3200, rating:4.5, sold:2300, image:"https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop", description:"Immersive sound profile with advanced active noise cancellation, crystal clear microphone, and long-lasting charging case battery life.", reviews:[{name:"Suman K.",date:"Sep 2, 2026",rating:5,comment:"Amazing battery backup and noise cancellation works great."}] },
  { id:2, title:"Men's Slim Fit Cotton Casual Shirt - Blue", category:"Fashion", price:1099, oldPrice:1600, rating:4.2, sold:850, image:"https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=400&fit=crop", description:"Breathable premium cotton fabric tailored with a modern slim fit. Perfect for casual outings and daily wear.", reviews:[{name:"Bibek R.",date:"Sep 4, 2026",rating:4,comment:"Fabric is soft and comfortable. Fits as expected."}] },
  { id:3, title:"Non-Stick Frying Pan 26cm with Wooden Handle", category:"Home appliance", price:750, oldPrice:1050, rating:4.6, sold:1400, image:"https://images.unsplash.com/photo-1556909114-44e3e70034e2?w=400&h=400&fit=crop", description:"Durable non-stick coating requiring minimal oil, featuring an ergonomic heat-resistant wooden handle.", reviews:[{name:"Sunita M.",date:"Sep 1, 2026",rating:5,comment:"Nothing sticks to it! Very easy to clean."}] },
  { id:4, title:"Hydrating Facial Vitamin C Glow Serum", category:"Beauty", price:1250, oldPrice:1999, rating:4.7, sold:920, image:"https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop", description:"Brightening antioxidant serum infused with botanical extracts to reduce dark spots and give your skin a natural radiant glow.", reviews:[{name:"Anita T.",date:"Sep 5, 2026",rating:5,comment:"Noticeably brightened my skin within a week of use!"}] },
  { id:5, title:"Professional Adjustable Fitness Yoga Mat", category:"Sports", price:999, oldPrice:1500, rating:4.4, sold:610, image:"https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop", description:"Anti-slip eco-friendly exercise mat with high-density cushioning to protect joints during yoga, pilates, and floor workouts.", reviews:[{name:"Rohan D.",date:"Aug 30, 2026",rating:4,comment:"Great grip, doesn't slide on tile floors."}] },
  { id:6, title:"Organic Himalayan Honey Jar 500g", category:"Groceries", price:650, oldPrice:850, rating:4.8, sold:3100, image:"https://images.unsplash.com/photo-1587049352851-8d4e89133924?w=400&h=400&fit=crop", description:"Raw, pure and unpasteurized organic wildflower honey harvested directly from pristine Himalayan beehives.", reviews:[{name:"Kiran P.",date:"Sep 3, 2026",rating:5,comment:"Authentic taste and high purity. Excellent quality!"}] },
  { id:7, title:"Interactive Educational Smart Robot Toy for Kids", category:"Toys", price:2499, oldPrice:3800, rating:4.3, sold:430, image:"https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=400&h=400&fit=crop", description:"Voice-controlled smart robot featuring walking, dancing, storytelling, and basic coding interaction for children.", reviews:[{name:"Deepak L.",date:"Aug 25, 2026",rating:4,comment:"My son loves playing with it. Very engaging."}] },
  { id:8, title:"Smart Fitness Activity Tracker Watch", category:"Electronics", price:2999, oldPrice:4999, rating:4.4, sold:1750, image:"https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop", description:"Track your heart rate, sleep patterns, daily steps, and workout modes with a vibrant color touchscreen and long battery life.", reviews:[{name:"Nabin C.",date:"Sep 6, 2026",rating:4,comment:"Step tracking is precise and battery lasts almost a week."}] },
  { id:9, title:"Women's Elegant Floral Summer Maxi Dress", category:"Fashion", price:1599, oldPrice:2499, rating:4.6, sold:940, image:"https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&h=400&fit=crop", description:"Flowy, lightweight fabric featuring a gorgeous floral print, ideal for summer parties and casual daytime outings.", reviews:[{name:"Sneha G.",date:"Sep 1, 2026",rating:5,comment:"Gorgeous dress! Fits beautifully and material is breezy."}] },
  { id:10, title:"Electric Stainless Steel Kettle 1.8L", category:"Home appliance", price:1399, oldPrice:2100, rating:4.5, sold:1620, image:"https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&h=400&fit=crop", description:"Rapid boiling technology with automatic shut-off and boil-dry protection in a sleek brushed stainless steel body.", reviews:[{name:"Bishal T.",date:"Aug 29, 2026",rating:5,comment:"Boils water in less than 3 minutes. Very handy."}] },
  { id:11, title:"Matte Liquid Lipstick Set (Pack of 4)", category:"Beauty", price:899, oldPrice:1499, rating:4.3, sold:1150, image:"https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&h=400&fit=crop", description:"Long-lasting, smudge-proof, and highly pigmented matte lip colors that keep your lips velvety smooth all day.", reviews:[{name:"Puja K.",date:"Sep 4, 2026",rating:4,comment:"Colors are stunning and stay on for hours."}] },
  { id:12, title:"Stainless Steel Insulated Sports Water Bottle 1L", category:"Sports", price:850, oldPrice:1300, rating:4.7, sold:2100, image:"https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=400&fit=crop", description:"Double-wall vacuum insulation keeps your drinks ice-cold for 24 hours or piping hot for up to 12 hours.", reviews:[{name:"Anish B.",date:"Sep 2, 2026",rating:5,comment:"Keeps water cold even under direct sun during treks."}] },
  { id:13, title:"Basmati Premium Rice 5kg Bag", category:"Groceries", price:950, oldPrice:1200, rating:4.9, sold:4500, image:"https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop", description:"Extra-long grain aromatic aged basmati rice that fluffs up perfectly for daily meals and special occasion biryanis.", reviews:[{name:"Sarita R.",date:"Sep 7, 2026",rating:5,comment:"Very aromatic and delicious grains. Best quality rice."}] },
  { id:14, title:"Remote Control High-Speed Racing Monster Truck", category:"Toys", price:2199, oldPrice:3500, rating:4.6, sold:720, image:"https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=400&h=400&fit=crop", description:"All-terrain heavy-duty shockproof RC truck built for rough outdoor dirt tracks and high-speed stunt racing.", reviews:[{name:"Prabin M.",date:"Aug 27, 2026",rating:5,comment:"Super fast and rugged build. Handles bumps easily."}] },
  { id:15, title:"Portable Wireless Bluetooth Speaker with RGB Lights", category:"Electronics", price:1699, oldPrice:2800, rating:4.5, sold:1890, image:"https://images.unsplash.com/photo-1545454675-3531b543be5d?w=400&h=400&fit=crop", description:"Punchy bass delivery with dynamic pulsing LED light shows, waterproof body, and extended Bluetooth wireless range.", reviews:[{name:"Siddharth J.",date:"Sep 3, 2026",rating:4,comment:"Sound is loud and clear for house parties."}] },
  { id:16, title:"Unisex Classic Aviator Sunglasses", category:"Fashion", price:799, oldPrice:1300, rating:4.2, sold:1040, image:"https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop", description:"Timeless metal frame design featuring UV400 protection lenses to shield your eyes in style.", reviews:[{name:"Manish S.",date:"Aug 24, 2026",rating:4,comment:"Looks sleek and blocks glare effectively."}] },
  { id:17, title:"Automatic Electric Coffee Grinder", category:"Home appliance", price:1999, oldPrice:3100, rating:4.7, sold:530, image:"https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&h=400&fit=crop", description:"One-touch stainless steel blade grinder for coffee beans, spices, and nuts with custom texture control.", reviews:[{name:"Prashant N.",date:"Sep 5, 2026",rating:5,comment:"Grinds coffee beans evenly in seconds."}] },
  { id:18, title:"Argan Oil Hair Repair Mask 250ml", category:"Beauty", price:1150, oldPrice:1799, rating:4.8, sold:810, image:"https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=400&h=400&fit=crop", description:"Deep conditioning Moroccan argan oil treatment that repairs dry, damaged, and frizzy hair instantly.", reviews:[{name:"Shreya D.",date:"Sep 6, 2026",rating:5,comment:"Made my hair super silky and smooth."}] },
  { id:19, title:"Adjustable Hand Grip Strengthener Set", category:"Sports", price:499, oldPrice:850, rating:4.4, sold:1340, image:"https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=400&fit=crop", description:"Ergonomic resistance-adjustable hand grippers designed to build forearm muscle and finger dexterity.", reviews:[{name:"Aakash P.",date:"Aug 26, 2026",rating:4,comment:"Good quality resistance springs."}] },
  { id:20, title:"Crunchy Mixed Dry Fruits & Nuts Pack 400g", category:"Groceries", price:799, oldPrice:1100, rating:4.9, sold:2200, image:"https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400&h=400&fit=crop", description:"A premium healthy assortment of almonds, cashews, pistachios, and raisins for a nutritious daily snack.", reviews:[{name:"Rita M.",date:"Sep 4, 2026",rating:5,comment:"Fresh and crunchy nuts. High quality packaging."}] },
  { id:21, title:"Wooden Brain Teaser Puzzle Box for Kids", category:"Toys", price:599, oldPrice:950, rating:4.5, sold:670, image:"https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=400&h=400&fit=crop", description:"Eco-friendly interlocking wooden block puzzle designed to enhance cognitive logic and problem-solving skills.", reviews:[{name:"Kamal B.",date:"Aug 22, 2026",rating:5,comment:"Great for kids' brain development. Solid wood."}] },
  { id:22, title:"Over-Ear Gaming Headset with Mic", category:"Electronics", price:2299, oldPrice:3800, rating:4.6, sold:1540, image:"https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&h=400&fit=crop", description:"Surround sound immersion, noise-isolating memory foam earcups, and an adjustable high-sensitivity boom microphone.", reviews:[{name:"Samir T.",date:"Sep 7, 2026",rating:5,comment:"Very comfortable for long gaming sessions and crisp mic."}] },
  { id:23, title:"Men's Casual Canvas Fashion Sneakers", category:"Fashion", price:1799, oldPrice:2600, rating:4.3, sold:1120, image:"https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400&h=400&fit=crop", description:"Lightweight, durable rubber-soled canvas shoes styled for versatile everyday streetwear and casual use.", reviews:[{name:"Nischal K.",date:"Aug 31, 2026",rating:4,comment:"Stylish and lightweight for daily walking."}] },
  { id:24, title:"Mini USB Rechargeable Handheld Desk Fan", category:"Home appliance", price:699, oldPrice:1100, rating:4.4, sold:1980, image:"https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=400&fit=crop", description:"Compact 3-speed portable cooling fan powered via USB battery, perfect for office desks and bedside tables.", reviews:[{name:"Laxmi S.",date:"Sep 2, 2026",rating:4,comment:"Surprisingly powerful airflow for its compact size."}] },
  { id:25, title:"Charcoal Deep Cleansing Peel-Off Face Mask", category:"Beauty", price:450, oldPrice:750, rating:4.2, sold:1450, image:"https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop", description:"Activated bamboo charcoal formula that deeply purifies pores, removes blackheads, and controls excess facial oil.", reviews:[{name:"Binod C.",date:"Aug 29, 2026",rating:4,comment:"Clears out blackheads cleanly."}] },
  { id:26, title:"Resistance Exercise Bands Set (5 Levels)", category:"Sports", price:799, oldPrice:1299, rating:4.7, sold:1820, image:"https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=400&fit=crop", description:"Color-coded stackable latex resistance bands designed for strength training, physical therapy, and home fitness routines.", reviews:[{name:"Sunil G.",date:"Sep 5, 2026",rating:5,comment:"Versatile and durable bands for working out anywhere."}] },
  { id:27, title:"Organic Green Tea Leaves Tin 200g", category:"Groceries", price:550, oldPrice:800, rating:4.6, sold:1280, image:"https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400&h=400&fit=crop", description:"Hand-picked high-antioxidant pure green tea leaves packed with natural flavor and detoxifying benefits.", reviews:[{name:"Tara W.",date:"Sep 1, 2026",rating:5,comment:"Refreshing taste and great for morning metabolism."}] },
  { id:28, title:"Plush Soft Teddy Bear Stuffed Toy 60cm", category:"Toys", price:1299, oldPrice:2000, rating:4.9, sold:960, image:"https://images.unsplash.com/photo-1559523161-0fc0d8b38a7a?w=400&h=400&fit=crop", description:"Extremely huggable, hypoallergenic, soft plush giant teddy bear stuffed toy with premium velvet exterior.", reviews:[{name:"Pratima N.",date:"Sep 6, 2026",rating:5,comment:"So soft and fluffy! Wonderful gift item."}] },
  { id:29, title:"Fast-Charging 20000mAh Power Bank", category:"Electronics", price:2499, oldPrice:3999, rating:4.7, sold:2410, image:"https://images.unsplash.com/photo-1615526675159-e248c3021d3f?w=400&h=400&fit=crop", description:"High-capacity dual-output portable power bank featuring rapid charging speeds and smart circuit protection.", reviews:[{name:"Suman B.",date:"Sep 7, 2026",rating:5,comment:"Charges my phone multiple times on a single charge."}] },
  { id:30, title:"Stainless Steel Kitchen Knife Set with Block", category:"Home appliance", price:2199, oldPrice:3400, rating:4.8, sold:890, image:"https://images.unsplash.com/photo-1593618998160-e34014e67546?w=400&h=400&fit=crop", description:"Professional razor-sharp multi-purpose stainless steel kitchen knives housed in a clean wooden storage block.", reviews:[{name:"Anita S.",date:"Sep 3, 2026",rating:5,comment:"Extremely sharp and looks very professional on the counter."}] }
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/everest_mart');
    console.log('Connected to MongoDB for seeding...');

const hashedPassword = await bcrypt.hash('1945bomb', 10);
    await User.findOneAndUpdate(
      { email: 'yuhanraut@gmail.com' },
      { name: 'Admin', email: 'yuhanraut@gmail.com', password: hashedPassword, role: 'admin' },
      { upsert: true }
    );
    console.log('Admin user set (yuhanraut@gmail.com / 1945bomb)');

    await Product.deleteMany({});
    console.log('Cleared old products.');

    await Product.insertMany(products);
    console.log('Database successfully seeded with 30 products!');

    await mongoose.disconnect();
    console.log('Disconnected from MongoDB.');
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedDatabase();
